export const COUNTRIES = [
  { code: 'AE', name: 'United Arab Emirates', emoji: '🇦🇪' },
  { code: 'AF', name: 'Afghanistan', emoji: '🇦🇫' },
  { code: 'AL', name: 'Albania', emoji: '🇦🇱' },
  { code: 'AT', name: 'Austria', emoji: '🇦🇹' },
  { code: 'AU', name: 'Australia', emoji: '🇦🇺' },
  { code: 'BE', name: 'Belgium', emoji: '🇧🇪' },
  { code: 'BG', name: 'Bulgaria', emoji: '🇧🇬' },
  { code: 'BR', name: 'Brazil', emoji: '🇧🇷' },
  { code: 'CA', name: 'Canada', emoji: '🇨🇦' },
  { code: 'CH', name: 'Switzerland', emoji: '🇨🇭' },
  { code: 'CN', name: 'China', emoji: '🇨🇳' },
  { code: 'CY', name: 'Cyprus', emoji: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', emoji: '🇨🇿' },
  { code: 'DE', name: 'Germany', emoji: '🇩🇪' },
  { code: 'DK', name: 'Denmark', emoji: '🇩🇰' },
  { code: 'ES', name: 'Spain', emoji: '🇪🇸' },
  { code: 'FI', name: 'Finland', emoji: '🇫🇮' },
  { code: 'FR', name: 'France', emoji: '🇫🇷' },
  { code: 'GB', name: 'United Kingdom', emoji: '🇬🇧' },
  { code: 'GR', name: 'Greece', emoji: '🇬🇷' },
  { code: 'HK', name: 'Hong Kong', emoji: '🇭🇰' },
  { code: 'HU', name: 'Hungary', emoji: '🇭🇺' },
  { code: 'ID', name: 'Indonesia', emoji: '🇮🇩' },
  { code: 'IE', name: 'Ireland', emoji: '🇮🇪' },
  { code: 'IL', name: 'Israel', emoji: '🇮🇱' },
  { code: 'IN', name: 'India', emoji: '🇮🇳' },
  { code: 'IT', name: 'Italy', emoji: '🇮🇹' },
  { code: 'JP', name: 'Japan', emoji: '🇯🇵' },
  { code: 'KR', name: 'South Korea', emoji: '🇰🇷' },
  { code: 'LU', name: 'Luxembourg', emoji: '🇱🇺' },
  { code: 'MX', name: 'Mexico', emoji: '🇲🇽' },
  { code: 'MY', name: 'Malaysia', emoji: '🇲🇾' },
  { code: 'NL', name: 'Netherlands', emoji: '🇳🇱' },
  { code: 'NO', name: 'Norway', emoji: '🇳🇴' },
  { code: 'NZ', name: 'New Zealand', emoji: '🇳🇿' },
  { code: 'PH', name: 'Philippines', emoji: '🇵🇭' },
  { code: 'PL', name: 'Poland', emoji: '🇵🇱' },
  { code: 'PT', name: 'Portugal', emoji: '🇵🇹' },
  { code: 'RO', name: 'Romania', emoji: '🇷🇴' },
  { code: 'RU', name: 'Russia', emoji: '🇷🇺' },
  { code: 'SE', name: 'Sweden', emoji: '🇸🇪' },
  { code: 'SG', name: 'Singapore', emoji: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', emoji: '🇸🇰' },
  { code: 'TH', name: 'Thailand', emoji: '🇹🇭' },
  { code: 'TR', name: 'Turkey', emoji: '🇹🇷' },
  { code: 'TW', name: 'Taiwan', emoji: '🇹🇼' },
  { code: 'UA', name: 'Ukraine', emoji: '🇺🇦' },
  { code: 'US', name: 'United States', emoji: '🇺🇸' },
  { code: 'VN', name: 'Vietnam', emoji: '🇻🇳' },
]

export function getCountryByCode(code: string) {
  return COUNTRIES.find((c) => c.code === code)
}

export function getCountriesForFilter() {
  return COUNTRIES.sort((a, b) => a.name.localeCompare(b.name))
}
