export const COUNTRIES = [
  { code: 'AE', name: 'United Arab Emirates', emoji: '🇦🇪' },
  { code: 'AF', name: 'Afghanistan', emoji: '🇦🇫' },
  { code: 'AL', name: 'Albania', emoji: '🇦🇱' },
  { code: 'AM', name: 'Armenia', emoji: '🇦🇲' },
  { code: 'AO', name: 'Angola', emoji: '🇦🇴' },
  { code: 'AR', name: 'Argentina', emoji: '🇦🇷' },
  { code: 'AT', name: 'Austria', emoji: '🇦🇹' },
  { code: 'AU', name: 'Australia', emoji: '🇦🇺' },
  { code: 'AZ', name: 'Azerbaijan', emoji: '🇦🇿' },
  { code: 'BD', name: 'Bangladesh', emoji: '🇧🇩' },
  { code: 'BE', name: 'Belgium', emoji: '🇧🇪' },
  { code: 'BG', name: 'Bulgaria', emoji: '🇧🇬' },
  { code: 'BH', name: 'Bahrain', emoji: '🇧🇭' },
  { code: 'BN', name: 'Brunei', emoji: '🇧🇳' },
  { code: 'BO', name: 'Bolivia', emoji: '🇧🇴' },
  { code: 'BR', name: 'Brazil', emoji: '🇧🇷' },
  { code: 'BW', name: 'Botswana', emoji: '🇧🇼' },
  { code: 'CA', name: 'Canada', emoji: '🇨🇦' },
  { code: 'CD', name: 'Democratic Republic of Congo', emoji: '🇨🇩' },
  { code: 'CG', name: 'Congo', emoji: '🇨🇬' },
  { code: 'CH', name: 'Switzerland', emoji: '🇨🇭' },
  { code: 'CI', name: 'Ivory Coast', emoji: '🇨🇮' },
  { code: 'CL', name: 'Chile', emoji: '🇨🇱' },
  { code: 'CM', name: 'Cameroon', emoji: '🇨🇲' },
  { code: 'CN', name: 'China', emoji: '🇨🇳' },
  { code: 'CO', name: 'Colombia', emoji: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', emoji: '🇨🇷' },
  { code: 'CU', name: 'Cuba', emoji: '🇨🇺' },
  { code: 'CY', name: 'Cyprus', emoji: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', emoji: '🇨🇿' },
  { code: 'DE', name: 'Germany', emoji: '🇩🇪' },
  { code: 'DK', name: 'Denmark', emoji: '🇩🇰' },
  { code: 'DO', name: 'Dominican Republic', emoji: '🇩🇴' },
  { code: 'DZ', name: 'Algeria', emoji: '🇩🇿' },
  { code: 'EC', name: 'Ecuador', emoji: '🇪🇨' },
  { code: 'EG', name: 'Egypt', emoji: '🇪🇬' },
  { code: 'ES', name: 'Spain', emoji: '🇪🇸' },
  { code: 'ET', name: 'Ethiopia', emoji: '🇪🇹' },
  { code: 'FI', name: 'Finland', emoji: '🇫🇮' },
  { code: 'FJ', name: 'Fiji', emoji: '🇫🇯' },
  { code: 'FK', name: 'Falkland Islands', emoji: '🇫🇰' },
  { code: 'FR', name: 'France', emoji: '🇫🇷' },
  { code: 'GB', name: 'United Kingdom', emoji: '🇬🇧' },
  { code: 'GE', name: 'Georgia', emoji: '🇬🇪' },
  { code: 'GH', name: 'Ghana', emoji: '🇬🇭' },
  { code: 'GR', name: 'Greece', emoji: '🇬🇷' },
  { code: 'GT', name: 'Guatemala', emoji: '🇬🇹' },
  { code: 'HK', name: 'Hong Kong', emoji: '🇭🇰' },
  { code: 'HN', name: 'Honduras', emoji: '🇭🇳' },
  { code: 'HT', name: 'Haiti', emoji: '🇭🇹' },
  { code: 'HU', name: 'Hungary', emoji: '🇭🇺' },
  { code: 'ID', name: 'Indonesia', emoji: '🇮🇩' },
  { code: 'IE', name: 'Ireland', emoji: '🇮🇪' },
  { code: 'IL', name: 'Israel', emoji: '🇮🇱' },
  { code: 'IN', name: 'India', emoji: '🇮🇳' },
  { code: 'IQ', name: 'Iraq', emoji: '🇮🇶' },
  { code: 'IR', name: 'Iran', emoji: '🇮🇷' },
  { code: 'IT', name: 'Italy', emoji: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', emoji: '🇯🇲' },
  { code: 'JO', name: 'Jordan', emoji: '🇯🇴' },
  { code: 'JP', name: 'Japan', emoji: '🇯🇵' },
  { code: 'KE', name: 'Kenya', emoji: '🇰🇪' },
  { code: 'KH', name: 'Cambodia', emoji: '🇰🇭' },
  { code: 'KR', name: 'South Korea', emoji: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', emoji: '🇰🇼' },
  { code: 'KZ', name: 'Kazakhstan', emoji: '🇰🇿' },
  { code: 'LA', name: 'Laos', emoji: '🇱🇦' },
  { code: 'LB', name: 'Lebanon', emoji: '🇱🇧' },
  { code: 'LK', name: 'Sri Lanka', emoji: '🇱🇰' },
  { code: 'LU', name: 'Luxembourg', emoji: '🇱🇺' },
  { code: 'LY', name: 'Libya', emoji: '🇱🇾' },
  { code: 'MA', name: 'Morocco', emoji: '🇲🇦' },
  { code: 'MC', name: 'Monaco', emoji: '🇲🇨' },
  { code: 'MG', name: 'Madagascar', emoji: '🇲🇬' },
  { code: 'MM', name: 'Myanmar', emoji: '🇲🇲' },
  { code: 'MN', name: 'Mongolia', emoji: '🇲🇳' },
  { code: 'MT', name: 'Malta', emoji: '🇲🇹' },
  { code: 'MU', name: 'Mauritius', emoji: '🇲🇺' },
  { code: 'MX', name: 'Mexico', emoji: '🇲🇽' },
  { code: 'MY', name: 'Malaysia', emoji: '🇲🇾' },
  { code: 'MZ', name: 'Mozambique', emoji: '🇲🇿' },
  { code: 'NA', name: 'Namibia', emoji: '🇳🇦' },
  { code: 'NG', name: 'Nigeria', emoji: '🇳🇬' },
  { code: 'NI', name: 'Nicaragua', emoji: '🇳🇮' },
  { code: 'NL', name: 'Netherlands', emoji: '🇳🇱' },
  { code: 'NO', name: 'Norway', emoji: '🇳🇴' },
  { code: 'NP', name: 'Nepal', emoji: '🇳🇵' },
  { code: 'NZ', name: 'New Zealand', emoji: '🇳🇿' },
  { code: 'OM', name: 'Oman', emoji: '🇴🇲' },
  { code: 'PA', name: 'Panama', emoji: '🇵🇦' },
  { code: 'PE', name: 'Peru', emoji: '🇵🇪' },
  { code: 'PG', name: 'Papua New Guinea', emoji: '🇵🇬' },
  { code: 'PH', name: 'Philippines', emoji: '🇵🇭' },
  { code: 'PK', name: 'Pakistan', emoji: '🇵🇰' },
  { code: 'PL', name: 'Poland', emoji: '🇵🇱' },
  { code: 'PR', name: 'Puerto Rico', emoji: '🇵🇷' },
  { code: 'PT', name: 'Portugal', emoji: '🇵🇹' },
  { code: 'PY', name: 'Paraguay', emoji: '🇵🇾' },
  { code: 'QA', name: 'Qatar', emoji: '🇶🇦' },
  { code: 'RO', name: 'Romania', emoji: '🇷🇴' },
  { code: 'RU', name: 'Russia', emoji: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', emoji: '🇷🇼' },
  { code: 'SA', name: 'Saudi Arabia', emoji: '🇸🇦' },
  { code: 'SD', name: 'Sudan', emoji: '🇸🇩' },
  { code: 'SE', name: 'Sweden', emoji: '🇸🇪' },
  { code: 'SG', name: 'Singapore', emoji: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', emoji: '🇸🇰' },
  { code: 'SN', name: 'Senegal', emoji: '🇸🇳' },
  { code: 'SV', name: 'El Salvador', emoji: '🇸🇻' },
  { code: 'TH', name: 'Thailand', emoji: '🇹🇭' },
  { code: 'TN', name: 'Tunisia', emoji: '🇹🇳' },
  { code: 'TR', name: 'Turkey', emoji: '🇹🇷' },
  { code: 'TT', name: 'Trinidad and Tobago', emoji: '🇹🇹' },
  { code: 'TW', name: 'Taiwan', emoji: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', emoji: '🇹🇿' },
  { code: 'UA', name: 'Ukraine', emoji: '🇺🇦' },
  { code: 'UG', name: 'Uganda', emoji: '🇺🇬' },
  { code: 'US', name: 'United States', emoji: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', emoji: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', emoji: '🇺🇿' },
  { code: 'VE', name: 'Venezuela', emoji: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', emoji: '🇻🇳' },
  { code: 'ZA', name: 'South Africa', emoji: '🇿🇦' },
  { code: 'ZM', name: 'Zambia', emoji: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', emoji: '🇿🇼' },
]

export function getCountryByCode(code: string) {
  return COUNTRIES.find((c) => c.code === code)
}

export function getCountriesForFilter() {
  return COUNTRIES.sort((a, b) => a.name.localeCompare(b.name))
}
